#配置端口
server_port: 8080
# Hibernate 相关配置
spring:
  redis:
    database: 0 #数据索引默认为0
    host: 127.0.0.1 #服务器地址
    port: 6379  #端口
    password:   #密码默认为空
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

    lettuce:
      shutdown-timeout: 1000 # 连接超时时间（毫秒）
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect  # 方言
    generate-ddl: true
    hibernate:
      ddl-auto: update
    #open-in-view: true

  #数据池
  dbcp:
    max-active: 20
    max-wait: 60000
    initial-size: 1
    min-idle: 1
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    #模板视图解析器
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false

#数据库驱动
ms:
  db:
    driverClassName:  com.mysql.cj.jdbc.Driver
    #url
    url: jdbc:mysql://127.0.0.1:3306/huantai_test?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    #用户名
    username: root
    #用户密码
    password: 123456
    maxActive: 500
#自动建表采用update的方式
auto_create:
  table: update
#是否显示sql
my:
  show_sql: true
#日志配置


